
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/ubuntu/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/aarch64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Linux - 6.14.0-1011-oracle - aarch64
